# Generated by Django 5.0.1 on 2024-02-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_dta'),
    ]

    operations = [
        migrations.CreateModel(
            name='incoming_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('recurring', models.BooleanField()),
                ('term', models.CharField(max_length=20)),
                ('endDate', models.DateField()),
            ],
        ),
    ]
