# Generated by Django 5.0.1 on 2024-02-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_incoming_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming_data',
            name='new_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
