# Generated by Django 5.0.1 on 2024-02-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_incoming_data_new_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring', models.BooleanField()),
                ('term', models.CharField(max_length=20)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='incoming_data',
            name='name',
        ),
        migrations.AlterField(
            model_name='incoming_data',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
