# Generated by Django 5.0.1 on 2024-02-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_transaction_remove_incoming_data_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
